name: Release Charts

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install yq
        run: sudo snap install yq

      - name: Set appVersion in Chart.yaml to match tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Detected tag: $TAG"
          yq -i ".appVersion = \"$TAG\"" deploy/helm/Chart.yaml

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Copy README to charts
        run: cp README.md deploy/helm
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: deploy/helm
